[default]
address = "0.0.0.0"
limits = { forms = "64 kB", json = "1 MiB" }

[debug]
port = 8080
limits = { json = "10MiB" }

[nyc]
port = 9001

## don't use this secret_key! generate your own and keep it private!
[release]
port = 9999
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="

# more config https://github.com/SergioBenitez/Rocket/blob/v0.5-rc/examples/config/Rocket.toml